server:
  port: 8081
spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:postgresql://localhost:5432/amerbank
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
jpa:
  hibernate:
    ddl-auto:
    show-sql: true
  flyway:
    schemas: public
    enabled: true
    locations: classpath:db/migration
jwt:
  secret: u7SKcmP9z3LfA6NvTyExB1QdReGmZx2W
