spring:
  cloud:
    config:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration/auth

eureka:
  client:
    enabled: false
jwt:
  secret: "testsecret123456789test123456789secret"
  expirationMs: 3600000
  serviceTokenExpirationMs: 120000

