server:
  port: 8081

spring:
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/amerbank?currentSchema=auth
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  application:
    name: auth-server
jpa:
  hibernate:
    ddl-auto: create-drop
    show-sql: true
  flyway:
    schemas: auth
    enabled: false
    locations: classpath:db/migration/auth

jwt:
  secret: ${JWT_SECRET}

eureka:
  client:
    enabled: false

kafka:
  bootstrap-servers: dummy:9092
