server:
  port: 8086

spring:
  application:
    name: loan
  datasource:
    url: jdbc:postgresql://postgres:5432/amerbank
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: loan
  flyway:
    enabled: true
    locations: classpath:db/migration/loan
    schemas: loan

jwt:
  secret: ${JWT_SECRET}
  serviceTokenExpirationMs: 120000
  expirationMs: 3600000

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka

loan:
  prefix: LN
  body-digits: 10
  upper-bound: 10000000000
  max-attempts: 5
  min-amount: 100.00
  max-amount: 1000000.00
  min-term-months: 1
  max-term-months: 360
  account-service-base: http://account
  customer-service-base: http://customer
  endpoint-owned: /account/internal/owned
  endpoint-deposit: /account/internal/deposit
  endpoint-withdraw: /account/internal/withdraw
  endpoint-payment: /account/internal/payment
