apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
  namespace: amerbank

type: Opaque
data:
  jwt-secret: dlBhQndJc2hybUk5Mm5BN2tQbm9yMUttSXd2eXU5Z2poQXBKZmU5cm5obg==
  spring-profiles-active: a3ViZXJuZXRlcw==
  config-server-url: aHR0cDovL2NvbmZpZy1zZXJ2ZXI6ODA4MA==

